# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('marcha', models.CharField(choices=[('Com Marcha', 'Com Marcha'), ('Sem Marcha', 'Sem Marcha')], default='Sem Marcha', max_length=10)),
                ('marcaDoCambio', models.CharField(max_length=100)),
                ('dono', models.CharField(max_length=100)),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
